# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "custom pom"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "custom "
      include: "scope"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
       dev-dependencies:
          # Define patterns to include dependencies in the group (based on
          # dependency name)
          applies-to: security-updates # Applies the group rule to security updates
          patterns:
            - "*"  
    open-pull-requests-limit: 0
    labels:
      - "dependabot"
      - "vulnerability"
    commit-message:
      prefix: "Vulnerability Update"
      include: "scope"
